openapi: "3.0.1"

info:
  title: "arg api"
  version: "1"
  description: arg api

servers:
  - url: http://localhost:8080
    description: Local server
  - url: http://62.171.153.17:8080
    description: Dev server

tags:
  - name: Users
    description: Users api
  - name: HotelBooking
    description: Api to get booking information
  - name: ContactUs
    description: send email to the client
paths:

  /api/v1/users:
    get:
      summary: Get All users
      operationId: getAllUsers
      tags:
        - Users
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/User"
    put:
      summary: Updates a list of users
      operationId: updateUsers
      tags:
        - Users
      requestBody:
        description: Payload to edit the user
        required: true
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: "#/components/schemas/UpdateUserRequest"
      responses:
        200:
          description: Updates users
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/User"
    post:
      summary: Create a list of users
      operationId: createUsers
      tags:
        - Users
      requestBody:
        description: Payload to create the user
        required: true
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: "#/components/schemas/CreateUser"
      responses:
        200:
          description: Updates users
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/User"

  /api/v1/users/{userIds}:
    delete:
      summary: Delete a list of users by id
      operationId: deleteUsersById
      tags:
        - Users
      parameters:
        - name: userIds
          in: path
          required: true
          schema:
            type: array
            items:
              type: integer
              format: int64
              minimum: 1
            minItems: 1
      responses:
        '200':
          description: Successful deletion
        '400':
          description: Bad Request - Invalid input
        '404':
          description: Not Found - Items not found
  /api/v1/hotel/rooms:
    get:
      summary: Get list of rooms
      operationId: getRoomsForGivenRangeOfDate
      tags:
        - HotelBooking
      parameters:
        - name: start-date
          in: query
          schema:
            type: string
            format: date
        - name: end-date
          in: query
          schema:
            type: string
            format: date
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/RoomPrototype"

  /api/v1/contact-us/email:
    post:
      summary: Send an email to the owner
      operationId: sendEmail
      tags:
        - ContactUs
      requestBody:
        description: Necessary Data to send the email
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ConfernceMailStructure"
      responses:
        200:
          description: OK



components:
  schemas:
    User:
      $ref: "./schemas/user.yaml"
    CreateUser:
      $ref: "./schemas/CreateUser.yaml"
    UpdateUserRequest:
      $ref: "./schemas/UpdateUserRequest.yaml"
    RoomPrototype:
      $ref: "./schemas/hotel/Booking/RoomPrototype.yaml"
    ConfernceMailStructure:
      $ref: "./schemas/hotel/Booking/Mail/ConfernceMailStructure.yaml"

