services:
  # PostgreSQL Service Configuration
  postgres:
    image: 'postgres:16.1-alpine'
    container_name: ecm-db
    environment:
      POSTGRES_DB: e-commerce
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_USER: $POSTGRES_USER
    ports:
      - '5432:5432'
    networks:
      - ecm
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    build:
      context: .
      dockerfile: ecm-local/DockerFile
      args:
        build_version: "0.0.1-SNAPSHOT"
    environment:
      SPRING_PROFILES_ACTIVE: $SPRING_PROFILES_ACTIVE
      SWAGGER_ENABLED: true
      DATABASE_URL: jdbc:postgresql://postgres/e-commerce
    ports:
      - "8080:8080"
      - "8000:8000"
      - "3128:3128"
    volumes:
      - api:/usr/app/ecm
    networks:
      - ecm
    depends_on:
      postgres:
        condition: service_started

volumes:
  pgdata:
  api:

networks:
  ecm:
    driver: bridge
