include:
  - docker-compose-base.yaml


services:

  api:
    image: blou5/arg-api:latest
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
      SWAGGER_ENABLED: true
      DATABASE_URL: jdbc:postgresql://postgres/arg
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      whatsapp_api_token: ${whatsapp_api_token}
      security_key: ${security_key_file}
      security_password: ${security_password}

    volumes:
      - ${ARG_SPRING_BOOT_LOGS_PATH}:/app/logs
      - ${security_key_file}:/etc/ssl/keystore.p12
    ports:
      - "8080:8080"
      - "8000:8000"
      - "3128:3128"
    networks:
      - arg
    depends_on:
      postgres:
        condition: service_started
