# application configuration
server:
  shutdown: graceful
spring:
  main:
    allow-circular-references: true
    web-application-type: SERVLET
  jpa:
    database: default
    generate-ddl: false
#    open-in-view: false TODO #https://stackoverflow.com/questions/30549489/what-is-this-spring-jpa-open-in-view-true-property-in-spring-boot
    properties:
      hibernate:
        cache.use_second_level_cache: false
        generate_statistics: false
        default_schema: public
        format_sql: true
    show-sql: ${SHOW_SQL:false}
  datasource:
    hikari:
      maximum-pool-size: 15
      connection-timeout: 10000
      initialization-fail-timeout: 60000
      register-mbeans: true
    driver-class-name: org.postgresql.Driver
    url: ${DATABASE_URL:jdbc:postgresql://localhost/arg}
    username: ${DATABASE_USER:arg}
    password: ${DATABASE_PASSWORD:arg}
  mail:
    host: ${EMAIL_HOST}
    port: ${EMAIL_PORT}
    username: ${EMAIL_USERNAME}
    password: ${EMAIL_PASSWORD}
    default-encoding: UTF-8
    properties:
      mail:
        mime:
          chartset: UTF
        smtp:
          writetimeout: 10000
          connectiontimeout: 10000
          timeout: 10000
          auth: true
          starttls:
            enable: ${STARTTLS:true}
            required: ${REQUIRED:true}
      verify:
        host: ${VERIFY_EMAIL_HOST}


  lifecycle:
    timeout-per-shutdown-phase: 10s
  profiles:
    active: local
swagger-ui:
  enabled: ${SWAGGER_ENABLED:true}
  configuration-name: ${SWAGGER_UI_CONFIGURATION_NAME:keycloak}

whatsapp:
  api:
    url: https://graph.facebook.com/v19.0/311469262042262/messages
    token: EAAFvoTBlQ4YBO7ATvNtI5pL4rt0gX1ngAQMKXyHbqY4rfEHu66RE96fvNqD3BtvB1udGV14NZAPjt8oynheIObxBK6nXEAkr4NHYcdQ3S3tyb12jSlU2lYJsyHBbJND8ZBhmOfYx4injlM41NniGVCESkNxSWuBsF0qMpPiHJOobDGKh3bvYF7rrEV5ZAoErPFZBtkPcsnxLJi4p
    to: 355676923049