# application configuration
server:
  shutdown: graceful
spring:
  main:
    allow-circular-references: true
    web-application-type: SERVLET
  jpa:
    database: default
    generate-ddl: false
#    open-in-view: false TODO #https://stackoverflow.com/questions/30549489/what-is-this-spring-jpa-open-in-view-true-property-in-spring-boot
    properties:
      hibernate:
        cache.use_second_level_cache: false
        generate_statistics: false
        default_schema: public
        format_sql: true
    show-sql: ${SHOW_SQL:false}
  datasource:
    hikari:
      maximum-pool-size: 15
      connection-timeout: 10000
      initialization-fail-timeout: 60000
      register-mbeans: true
    driver-class-name: org.postgresql.Driver
    url: ${DATABASE_URL:jdbc:postgresql://localhost/e-commerce}
    username: ${DATABASE_USER:ecm}
    password: ${DATABASE_PASSWORD:ecm}
  lifecycle:
    timeout-per-shutdown-phase: 10s
  profiles:
    active: local
swagger-ui:
  enabled: ${SWAGGER_ENABLED:true}
  configuration-name: ${SWAGGER_UI_CONFIGURATION_NAME:keycloak}