server:
  shutdown: graceful
  port: 8080
  ssl:
    key-store: /etc/ssl/keystore.p12
    key-store-password: ${security_password}
    key-store-type: PKCS12


allowed-origins: http://45.90.121.140,http://45.90.121.140:80,http://45.90.121.140:443,http://quantum-pixel.eu,https://quantum-pixel.eu, https://aragosta.al, http://aragosta.al

# Email Config

EMAIL_HOST: smtp.gmail.com
EMAIL_PORT: 587
EMAIL_USERNAME: ${GMAIL}
EMAIL_PASSWORD: ${GMAIL_PASSWORD}
VERIFY_EMAIL_HOST: http://localhost:8080
RESERVATION_EMAIL_RECEIVER: reservation@aragosta.al

IMAP_USERNAME: ${GMAIL_IMAP}
IMAP_PASSWORD: ${GMAIL_PASSWORD}
IMAP_HOST: imap.gmail.com
IMAP_PORT: 993


whatsapp:
  api:
    phone_number_id: ${whatsapp_api_phone_number_id:433727949813085}
