allowed-origins: http://62.171.153.17,http://62.171.153.17:4200,http://62.171.153.17:4100,http://localhost:4200

# Email Config

EMAIL_HOST: smtp.gmail.com
EMAIL_PORT: 587
EMAIL_USERNAME: ${GMAIL}
EMAIL_PASSWORD: ${GMAIL_PASSWORD}
VERIFY_EMAIL_HOST: http://localhost:8080

IMAP_USERNAME: ${GMAIL_IMAP}
IMAP_PASSWORD: ${GMAIL_PASSWORD}
IMAP_HOST: imap.gmail.com
IMAP_PORT: 993

whatsapp:
  api:
    phone_number_id: ${whatsapp_api_phone_number_id:433727949813085}
