
spring:
  docker:
    compose:
      file: arg-docker/arg-local/docker-compose-base.yaml
  jpa:
    show-sql: true


allowed-origins: http://localhost:4200, http://localhost:5211, *
server:
  address: 192.168.111.8


# Email Config

EMAIL_HOST: smtp.gmail.com
EMAIL_PORT: 587
EMAIL_USERNAME: testqpt8@gmail.com
EMAIL_PASSWORD: lbzhzuruwvudrbem

IMAP_USERNAME: testqpt8%40gmail.com
IMAP_PASSWORD: lbzhzuruwvudrbem
IMAP_HOST: imap.gmail.com
IMAP_PORT: 993
whatsapp:
  api:
    token: dummy_token
