
services:

  postgres:
    image: 'postgres:16.1-alpine'
    container_name: ecm-db
    environment:
      POSTGRES_DB: e-commerce
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_USER: ${DATABASE_USER}
    ports:
      - '5432:5432'
    networks:
      - ecm
    volumes:
      - pgdata:/var/lib/postgresql/data


volumes:
  pgdata:

networks:
  ecm:
    driver: bridge
