include:
  - docker-compose-base.yaml

services:

  api:
    build:
      context: ../..
      dockerfile: ecm-docker/ecm-local/DockerFile
      args:
        build_version: "0.0.1-SNAPSHOT"
    environment:
      SPRING_PROFILES_ACTIVE: local
      SWAGGER_ENABLED: true
      DATABASE_URL: jdbc:postgresql://postgres/e-commerce
    ports:
      - "8080:8080"
      - "8000:8000"
      - "3128:3128"
    volumes:
      - api:/usr/app/ecm
    networks:
      - ecm
    depends_on:
      postgres:
        condition: service_started

  # pgAdmin web UI
  pgadmin:
    image: dpage/pgadmin4
    container_name: ecm-pgadmin
    ports:
      - "5059:80"
    env_file:
      - .env
    volumes:
      - ./servers.json:/pgadmin4/servers.json
    depends_on:
      - postgres
    networks:
      - ecm

  py:
    container_name: ecm_db_initialize
    build:
      context: ../..
      dockerfile: ecm-docker/ecm-local/DbInitialize
    env_file:
      - .env
    networks:
      - ecm
    depends_on:
      api:
        condition: service_started

