name: Continuous Integration/Deployment

on:
  push:
    branches: [ "master" ]
    paths:
      - "src/**"
      - "ecm-docker/**"
  pull_request:
    branches: [ "master" ]
    paths:
      - "src/**"
      - "ecm-docker/**"
  workflow_dispatch:
    inputs:
      sync:
        description: "File synchronization"
        required: true
        default: "delta"
jobs:
  ci:
    uses: quantum-pixel-team/ci-cd-templates/.github/workflows/api-ci-gradle.yml@master
    secrets:
      git_token: ${{ secrets.GITHUB_TOKEN }}
      sonar_token: ${{ secrets.SONAR_TOKEN }}

  cd:
    needs: ci
#    if: github.event_name  == 'push'
    uses: quantum-pixel-team/ci-cd-templates/.github/workflows/common-cd.yml@master
    with:
      environment: "dev"
      docker-file-path: "Dockerfile"
      tag: "blou5/e-commerce:latest"
      local-path: "ecm-docker/dev"
      remote-path: "/home/luka_buziu22_gmail_com/docker-compose-api"
      artifact-path: "build/libs"
      deploy-script: "
              cd docker-compose-api &&
               docker compose pull &&
              docker compose up -d  "
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      HOST: ${{secrets.HOST}}
      SSH_USER: ${{secrets.SSH_USER}}
      SSH_PRIVATE_KEY: ${{secrets.SSH_PRIVATE_KEY}}
