DELETE FROM events;
INSERT INTO events (title, start_date, start_time, end_date, short_description, feature_image_url) VALUES
                                                                                                ('Live Music Night', '2024-05-15', '19:00', '2024-05-15', 'Join us for a night of delicious food and live music at our restaurant! Our talented musicians will be performing a mix of popular songs and classic hits while you enjoy a mouth-watering meal from our menu. Bring your friends and family for a fun and lively evening of dining and entertainment. Don`t miss out on this exciting event. Book your table now!', 'assets/events/live music night.png'),
                                                                                                ('Christmas Event', '2024-12-24', '18:00', '2024-12-24', 'Experience a Magical Christmas at Our Hotel/Restaurant! Celebrate the most wonderful time of the year with us as we transform our venue into a winter wonderland. Bring your family and friends to indulge in a festive feast and enjoy a memorable Christmas experience.', 'assets/events/chrismas event.png'),
                                                                                                ('New Year Party', '2024-12-31', '20:00', '2025-01-01', 'Join us for a dazzling New Year`s Eve celebration at our luxurious hotel/restaurant! Get ready to ring in the new year in style with an unforgettable night of delicious food, live music, and plenty of champagne. Don`t miss out on the ultimate New Year`s Eve experience at our hotel/restaurant. Book your table now!', 'assets/events/new year party.png'),
                                                                                                ('Nature 1', '2024-05-06', NULL, NULL, 'Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.', 'https://swiperjs.com/demos/images/nature-1.jpg'),
                                                                                                ('Nature 2', '2024-05-06', NULL, '2024-05-06', 'Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et', 'https://swiperjs.com/demos/images/nature-2.jpg'),
                                                                                                ('Nature 3', '2024-05-06', NULL, '2024-05-06', 'Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam', 'https://swiperjs.com/demos/images/nature-3.jpg'),
                                                                                                ('Nature 4', '2024-05-06', NULL, '2024-05-06', 'Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et', 'https://swiperjs.com/demos/images/nature-4.jpg'),
                                                                                                ('Nature 5', '2024-05-06', NULL, '2024-05-06', 'Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, ', 'https://swiperjs.com/demos/images/nature-5.jpg'),
                                                                                                ('Nature 6', '2024-05-06', NULL, '2024-05-06', 'Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr,', 'https://swiperjs.com/demos/images/nature-6.jpg'),
                                                                                                ('Nature 7', '2024-05-06', NULL, '2024-05-06', 'Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut', 'https://swiperjs.com/demos/images/nature-7.jpg'),
                                                                                                ('Nature 8', '2024-05-06', NULL, '2024-05-06', 'Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut', 'https://swiperjs.com/demos/images/nature-8.jpg'),
                                                                                                ('Nature 9', '2024-05-06', NULL, '2024-05-06', 'Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam', 'https://swiperjs.com/demos/images/nature-9.jpg');
